apiVersion: v1
kind: Service
metadata:
  name: dealer-backend-service
spec:
  type: NodePort
  selector:
    app: dealer-backend-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080