apiVersion: v1
kind: ConfigMap
metadata:
  name: dealer-backend-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{.Release.Name}}-{{.Values.postgresql.nameOverride}}:5432/{{.Values.postgresql.postgresqlDatabase}}"
  SPRING_DATASOURCE_USERNAME: {{.Values.postgresql.postgresqlUsername}}

