apiVersion: v2
name: admin-frontend-service
version: 0.0.1
description: Dealer admin web app
type: application
sources:
  - https://github.com/GcSale/gs-admin-client
maintainers:
  - name: Yakovlev Denis
    email: de1m0s242@gmail.com
appVersion: "v0.0.1"